# Generated by Django 6.0.8 on 2026-10-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='dotmcinfo',
            name='dot_number',
        ),
        migrations.RemoveField(
            model_name='dotmcinfo',
            name='mc_number',
        ),
    ]
