# Generated by Django 6.0.8 on 2026-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_company_country_remove_dotmcinfo_dot_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('login_2fa', 'Login 2FA'), ('password_reset', 'Password Reset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
