# Generated by Django 6.0.8 on 2026-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcode_purpose_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotmcinfo',
            name='dot_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dotmcinfo',
            name='mc_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
