# Generated by Django 6.0.8 on 2026-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dotmcinfo_dot_number_dotmcinfo_mc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='reset_token',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
