# Generated by Django 6.0.8 on 2026-10-06 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('counter_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacityPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('cubic_feet', models.PositiveIntegerField()),
                ('equipment_type', models.CharField(choices=[('Any equipment', 'Any Equipment'), ('Box Truck', 'Box Truck'), ('Moving Trailer', 'Moving Trailer'), ('Dry Van (Side Door)', 'Dry Van (Side Door)')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('deactivated', 'Deactivated')], default='active', max_length=15)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacityOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_offers_sent', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.capacityposting')),
            ],
            options={
                'ordering': ['-offered_at'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('bidding', 'Bidding'), ('booked', 'Booked'), ('completed', 'Completed'), ('expired', 'Expired')], default='open', max_length=15)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('cubic_feet', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('equipment_type', models.CharField(choices=[('Any equipment', 'Any Equipment'), ('Box Truck', 'Box Truck'), ('Moving Trailer', 'Moving Trailer'), ('Dry Van (Side Door)', 'Dry Van (Side Door)')], max_length=30)),
                ('pricing_mode', models.CharField(choices=[('open_bidding', 'Open Bidding'), ('best_offer', 'Best Offer'), ('fixed', 'Fixed')], max_length=15)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public')], default='public', max_length=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_loads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(editable=False, max_length=20, unique=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='marketplace.bid')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_bookings', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_bookings', to=settings.AUTH_USER_MODEL)),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='marketplace.load')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.load'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='marketplace.load')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'countered'])), fields=('load', 'carrier'), name='unique_active_bid_per_carrier_load'),
        ),
    ]
