# Generated by Django 6.0.8 on 2026-10-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
    ]
