# Generated by Django 6.0.8 on 2026-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_booking_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_by_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_by_shipper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('in_transit', 'In Transit'), ('completed', 'Completed')], default='booked', max_length=15),
        ),
    ]
